name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t1.3
      id: t1-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.3
        setup-command: ''
        command: grep -q -E 'git.*add' answers/1.3 && grep -q -E 'git.*commit' answers/1.3
          && grep -q -E 'git.*push' answers/1.3
        timeout: 10
        max-score: 10
    - name: t1.4
      id: t1-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.4
        setup-command: ''
        command: grep -q -E 'git.*log' answers/1.4
        timeout: 10
        max-score: 10
    - name: t1.5
      id: t1-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.5
        setup-command: ''
        command: grep -q -i -E 'git.*log.*grep.*ginny' answers/1.5
        timeout: 10
        max-score: 10
    - name: t1.6
      id: t1-6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.6
        setup-command: ''
        command: grep -q -i -E 'git.*branch.*-a' answers/1.6
        timeout: 10
        max-score: 10
    - name: t1.7.1
      id: t1-7-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.7.1
        setup-command: ''
        command: grep -q -i -E 'git.*merge.*snape' answers/1.7.1
        timeout: 10
        max-score: 10
    - name: t1.7.2
      id: t1-7-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.7.2
        setup-command: ''
        command: grep -q -i -E 'git.*branch.*-d.*snape' answers/1.7.2
        timeout: 10
        max-score: 10
    - name: t1.8
      id: t1-8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.8
        setup-command: ''
        command: grep -q -i -E 'git.*checkout.*-b.*feature|git.*branch.*feature' answers/1.8
        timeout: 10
        max-score: 10
    - name: t1.9
      id: t1-9
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.9
        setup-command: ''
        command: grep -q -i -E 'git.*push.*--all' answers/1.9
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T1-3_RESULTS: "${{steps.t1-3.outputs.result}}"
        T1-4_RESULTS: "${{steps.t1-4.outputs.result}}"
        T1-5_RESULTS: "${{steps.t1-5.outputs.result}}"
        T1-6_RESULTS: "${{steps.t1-6.outputs.result}}"
        T1-7-1_RESULTS: "${{steps.t1-7-1.outputs.result}}"
        T1-7-2_RESULTS: "${{steps.t1-7-2.outputs.result}}"
        T1-8_RESULTS: "${{steps.t1-8.outputs.result}}"
        T1-9_RESULTS: "${{steps.t1-9.outputs.result}}"
      with:
        runners: t1-3,t1-4,t1-5,t1-6,t1-7-1,t1-7-2,t1-8,t1-9
